# Generated by Django 4.2.5 on 2023-10-28 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Football',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('jid', models.IntegerField()),
                ('coach', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('number', models.IntegerField()),
            ],
        ),
    ]
